packages:
  - packages/*
  - apps/*

allowBuilds:
  esbuild: true
  msgpackr-extract: false
  sharp: true

catalog:
  typescript: ^6.0.3
  "@types/node": ^26.1.1
  json5: ^2.2.3
  pathe: ^2.0.3
  tinyexec: ^1.2.4
  nypm: ^0.6.8
  jsonc-parser: ^3.3.1
  magicast: ^0.5.3
  consola: ^3.4.2
  defu: ^6.1.7
  vite-plus: 0.2.5
  "@biomejs/biome": "2.5.4"
  "@clack/prompts": ^1.7.0
  citty: ^0.2.2
  giget: ^3.3.0
  tinyglobby: ^0.2.17
  effect: 4.0.0-beta.91
  picocolors: ^1.1.1
  diff: ^9.0.0
  pkg-types: ^2.3.1
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5

minimumReleaseAgeExclude:
  - "@astrojs/markdown-satteri@0.3.2"
  - "@astrojs/starlight@0.41.0"
  - astro@7.0.2

onlyBuiltDependencies:
  - esbuild
  - sharp
overrides:
  vite: 'catalog:'
  dompurify: 3.4.12
  postcss: 8.5.25
  ws: 8.21.0
  read-yaml-file>js-yaml: 3.15.1
  yaml: 2.8.3
  fast-uri: 3.1.5
  tmp: 0.2.7
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
