import type { ProjectProfile } from '@xtarterize/core';

import { type PlopTemplateKey, plopTemplates } from './plop/index.js';

export { plopTemplates };

interface PlopAction {
  path: string;
  templateFile: string;
}

interface PlopGenerator {
  actions: Array<PlopAction>;
  description: string;
  name: string;
}

function action(path: string, templateFile: string): PlopAction {
  return { path, templateFile };
}

const HOOK_GENERATOR: PlopGenerator = {
  actions: [action('src/hooks/use{{pascalCase name}}.ts', 'plop/hook.ts.hbs')],
  description: 'Create a React hook',
  name: 'hook',
};

function componentGenerator(profile: ProjectProfile): PlopGenerator {
  const isVue = profile.framework === 'vue';
  const path = isVue
    ? 'src/components/{{pascalCase name}}.vue'
    : profile.framework === 'react-native'
      ? 'src/components/{{pascalCase name}}.tsx'
      : 'src/components/{{pascalCase name}}/{{pascalCase name}}.tsx';
  return {
    actions: [
      action(path, isVue ? 'plop/component.vue.hbs' : 'plop/component.tsx.hbs'),
    ],
    description: 'Create a reusable component',
    name: 'component',
  };
}

function buildGenerators(profile: ProjectProfile): Array<PlopGenerator> {
  const extension = profile.typescript ? 'ts' : 'js';
  const generators: Array<PlopGenerator> = [
    componentGenerator(profile),
    {
      actions: [
        action(`src/utils/{{kebabCase name}}.${extension}`, 'plop/util.ts.hbs'),
        action('src/utils/{{kebabCase name}}.test.ts', 'plop/util.test.ts.hbs'),
      ],
      description: 'Create a utility module',
      name: 'util',
    },
  ];

  if (profile.framework === 'node') {
    generators.push({
      actions: [
        action(
          `src/{{kebabCase name}}/index.${extension}`,
          'plop/module.ts.hbs'
        ),
      ],
      description: 'Create a Node module',
      name: 'module',
    });
  }

  if (profile.framework === 'react-native') {
    generators.push(
      {
        actions: [
          action(
            profile.router === 'expo-router'
              ? 'app/{{kebabCase name}}.tsx'
              : 'src/screens/{{pascalCase name}}Screen.tsx',
            'plop/screen.tsx.hbs'
          ),
        ],
        description: 'Create a React Native screen',
        name: 'screen',
      },
      HOOK_GENERATOR
    );
  }

  if (profile.framework === 'react') {
    generators.push(
      {
        actions: [
          action(
            profile.bundler === 'nextjs'
              ? 'app/{{kebabCase name}}/page.tsx'
              : 'src/pages/{{pascalCase name}}.tsx',
            'plop/page.tsx.hbs'
          ),
        ],
        description: 'Create an app page',
        name: 'page',
      },
      HOOK_GENERATOR
    );
  }

  return generators;
}

function renderGenerator(generator: PlopGenerator): string {
  const actions = generator.actions
    .map(
      ({ path, templateFile }) => `      {
        type: 'add',
        path: '${path}',
        templateFile: '${templateFile}',
      },`
    )
    .join('\n');

  return `  plop.setGenerator('${generator.name}', {
    description: '${generator.description}',
    prompts: [namePrompt],
    actions: [
${actions}
    ],
  })`;
}

export function getPlopTemplateFiles(
  profile: ProjectProfile
): Array<PlopTemplateKey> {
  const files: Array<PlopTemplateKey> = [];

  if (profile.framework === 'vue') {
    files.push('component.vue.hbs');
  } else {
    files.push('component.tsx.hbs');
  }

  files.push('util.ts.hbs', 'util.test.ts.hbs');

  if (profile.framework === 'node') {
    files.push('module.ts.hbs');
  }

  if (profile.framework === 'react-native') {
    files.push('screen.tsx.hbs', 'hook.ts.hbs');
  }

  if (profile.framework === 'react') {
    files.push('page.tsx.hbs', 'hook.ts.hbs');
  }

  return files;
}

export function renderPlopfile(profile: ProjectProfile): string {
  const generators = buildGenerators(profile).map(renderGenerator).join('\n\n');

  return `// Auto-generated by xtarterize

export default function (plop: any) {
  const namePrompt = {
    type: 'input',
    name: 'name',
    message: 'Name',
    validate: (value: string) => value.trim().length > 0 || 'A name is required',
  }

${generators}
}
`;
}
