export const CLI_TABLE_CHARS = {
  bottom: '─',
  'bottom-left': '└',
  'bottom-mid': '┴',
  'bottom-right': '┘',
  left: '│',
  'left-mid': '├',
  mid: '─',
  'mid-mid': '┼',
  middle: '│',
  right: '│',
  'right-mid': '┤',
  top: '─',
  'top-left': '┌',
  'top-mid': '┬',
  'top-right': '┐',
} as const;
